services:
  - type: web
    name: voltticket-api
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
